### ISSUE TITLE
error publishing geocode_addresses() results

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgisgeocode#17]
It looks like batch geocoding (`geocode_addresses()`) is not returning an sf obj (eg, that could be published using `publish_layer()` )- is that expected? If so, the function reference ("Details" section) should be updated.

``` r
# Example dataset from the Urban Institute
library(arcgis)
library(arcgisgeocode)

packageVersion("arcgisgeocode")
#> [1] '0.0.0.9006'
packageVersion("arcgislayers")
#> [1] '0.2.0'
packageVersion("arcgisutils")
#> [1] '0.2.0.9002'

set_arc_token(auth_user())

fp <- "https://urban-data-catalog.s3.amazonaws.com/drupal-root-live/2020/02/25/geocoding_test_data.csv"

to_geocode <- readr::read_csv(fp, readr::locale(encoding = "latin1"))[1:5, ] |>
  janitor::row_to_names(row_number = 1)

geocoded <- to_geocode |>
  dplyr::reframe(
    geocode_addresses(
      address = address,
      city = city,
      region = state,
      postal = zip
    )
  ) 

class(geocoded)
#> [1] "tbl_df"     "tbl"        "data.frame"

res1 <- publish_layer(geocoded, "batchgeocoded_points1")
#> Warning: CRS is missing from `x`
#> ℹ Using "EPSG:3857"
#> Error in `as_layer()`:
#> ! `geometry` cannot be converted into EsriJSON. Found a <XY> object, a
#>   <XY> object, a <XY> object, and a <XY> object
```

Publishing success upon converting to sf object:
``` r
geocoded <- to_geocode |>
  dplyr::reframe(
    geocode_addresses(
      address = address,
      city = city,
      region = state,
      postal = zip
    )
  ) |>
  sf::st_as_sf()

class(geocoded)
#> [1] "sf"         "tbl_df"     "tbl"        "data.frame"

res2 <- publish_layer(geocoded, "batchgeocoded_points2")
```

**Comment by JosiahParry** [comment]
The title of this issue is misleading, I think. That's because you're not trying to publish the result of `geocode_addresses()` but rather `reframe()`. 

I used reframe in the demo code to make it cleaner to write code that geocodes the addresses and results in a tibble with the same inputs and to allow the use of a pipe operator. 

`reframe()` keeps the class of its input, in this case, `to_geocode` is a `tibble`, so adding an sf object to it will result in a `tibble` 

If you use `geocode_addresses()` alone, the results will be an sf object. 

For example 

```r
geocoded <- geocode_addresses(
    address = to_geocode$address,
    city = to_geocode$city,
    region = to_geocode$state,
    postal = to_geocode$zip
  )
```

But that isn't as pretty :P

**Comment by mmachir** [comment]
it's like my eyes glazed over that reframe was even there. thank you for your patience!

**Comment by JosiahParry** [comment]
No, its a good point! And it means that reframe shouldn't be used in a demo _or_ if it is, it needs to be contextualized.
