### ISSUE TITLE
error publishing find_address_candidates() results

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgisgeocode#18]
Similar to #17, seeing an error when publishing results of `find_address_candidates()`, but not sure if this is to be expected. The results are an sf obj, but seeing an Esri json conversion error.

``` r
library(arcgis)
#> Attaching core arcgis packages:
#> → arcgisutils v0.2.0.9002
#> → arcgislayers v0.2.0
library(arcgisgeocode)
set_arc_token(auth_user())

# Find addresses -- output is sf. doesn't work.
candidates <- find_address_candidates(
  address = "esri",
  address2 = "380 new york street",
  city = "redlands",
  country_code = "usa",
  max_locations = 2
 )

class(candidates)
#> [1] "sf"         "data.frame"

res1 <- publish_layer(candidates, "geocoded_points1")
#> Error in `as_layer()`:
#> ! `extents` cannot be converted into EsriJSON. Found a double vector and
#>   a double vector
```

<sup>Created on 2024-05-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by JosiahParry** [comment]
This issue is because you cannot have nested columns in a FeatureClass. See below, each element is a a character vector of length 4

<img width="362" alt="image" src="https://github.com/R-ArcGIS/arcgisgeocode/assets/13534508/20e0f113-9fec-4895-8823-994dbf87b2ac">

If you deselect the list column e.g. `dplyr::select(candidates, -extent)` that should work.

I'm also noticing that while the error message is handy and better than what we previously had, its double counting the issue!
